### ISSUE TITLE
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

### ISSUE THREAD

**Issue by sametmax** [hactar-is/olaf#1]
Ran olaf on Python3.5 on Ubuntu 64 bits in a virtualenv:

    $ olaf freeze
    Traceback (most recent call last):
      File "/home/user/.local/share/virtualenvs/env/bin/olaf", line 11, in <module>
        sys.exit(main())
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/olaf/cli.py", line 21, in main
        freeze(prefix, write)
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/olaf/cli.py", line 27, in freeze
        frozen = pipfreeze()
      File "/home/user/.local/share/virtualenvs/env/lib/python3.5/site-packages/olaf/cli.py", line 183, in pipfreeze
        if line.startswith('-e '):
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by drcongo** [comment]
Fixed, Olaf should now be fully compatible with Python 3. I don't really use 3 much though so if you happen across any issues feel free to shout.
